apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: odf-operator-controller-manager-metrics-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odf-operator-controller-manager-metrics-service
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
