---
name: codespell

on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: codespell-project/actions-codespell@v2
      with:
        exclude_file: go.sum
        check_filenames: true
        check_hidden: true
        skip: vendor
