---
name: yamllint
on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ibiqlik/action-yamllint@v3
      with:
        config_file: ./.github/workflows/conf/yamllint.yaml
        file_or_dir: .  # Recursive on all yaml files
